async function loadBudgets(){
  const month=document.getElementById('budgetMonth').value;if(!month)return;
  const[y,m]=month.split('-'),monthStart=`${y}-${m}-01`;
  const{data:budgets,error:be}=await famQ(sb.from('budgets').select('*, categories(name,icon,color)')).eq('month',monthStart);if(be){toast(be.message,'error');return;}
  const{data:txs}=await famQ(sb.from('transactions').select('category_id,amount')).gte('date',`${y}-${m}-01`).lte('date',`${y}-${m}-31`).lt('amount',0);
  const spending={};(txs||[]).forEach(t=>{if(t.category_id)spending[t.category_id]=(spending[t.category_id]||0)+Math.abs(t.amount);});
  const grid=document.getElementById('budgetGrid');
  if(!budgets?.length){grid.innerHTML='<div class="empty-state" style="grid-column:1/-1"><div class="es-icon">🎯</div><p>Nenhum orçamento para este mês</p></div>';return;}
  grid.innerHTML=(budgets||[]).map(b=>{const spent=spending[b.category_id]||0,pct=b.amount>0?Math.min(100,(spent/b.amount)*100):0,over=spent>b.amount;return`<div class="card"><div class="card-header"><div style="display:flex;align-items:center;gap:8px"><span style="font-size:1.2rem">${b.categories?.icon||'📦'}</span><strong style="font-size:.9rem">${esc(b.categories?.name||'—')}</strong></div><div style="display:flex;gap:4px"><button class="btn-icon" onclick="openBudgetModal('${b.id}')">✏️</button><button class="btn-icon" onclick="deleteBudget('${b.id}')">🗑️</button></div></div><div style="display:flex;justify-content:space-between;margin-bottom:8px;font-size:.84rem"><span class="${over?'text-red':''}">Gasto: <strong>${fmt(spent)}</strong></span><span class="text-muted">Meta: ${fmt(b.amount)}</span></div><div class="progress"><div class="progress-bar" style="width:${pct}%;background:${over?'var(--red)':b.categories?.color||'var(--accent)'}"></div></div><div style="text-align:right;margin-top:5px;font-size:.72rem;color:var(--muted)">${pct.toFixed(0)}% utilizado</div></div>`;}).join('');
}
function openBudgetModal(){document.getElementById('budgetId').value='';setAmtField('budgetAmount', 0);document.getElementById('budgetCategory').innerHTML=state.categories.filter(c=>c.type==='despesa'&&!c.parent_id).map(c=>`<option value="${c.id}">${c.icon||''} ${c.name}</option>`).join('');openModal('budgetModal');}
async function saveBudget(){const mv=document.getElementById('budgetMonthInput').value;if(!mv)return;const[y,m]=mv.split('-');const data={category_id:document.getElementById('budgetCategory').value,month:`${y}-${m}-01`,amount:getAmtField('budgetAmount'),family_id:famId()};if(!data.category_id||!data.amount){toast('Preencha todos os campos','error');return;}const{error}=await sb.from('budgets').upsert(data,{onConflict:'category_id,month'});if(error){toast(error.message,'error');return;}toast('Orçamento salvo!','success');closeModal('budgetModal');loadBudgets();}
async function deleteBudget(id){if(!confirm('Excluir orçamento?'))return;await sb.from('budgets').delete().eq('id',id);loadBudgets();}
